- bin/dock-pulp-restore.py
- bin/dock-pulp.py
- dockpulp/__init__.py
Library should provide only the logger with empty logging handler. It is
up to clients to setup logging any way they wants to. Also with the
current way how logging was initialised it changed global logger.
See https://docs.python.org/3.1/library/logging.html#library-config for
detailed explanation.
Resolves: #1
> Leave logger setup of the library on the clients

- bin/dock-pulp.py
Running login command caused the problems:
$ dock-pulp.py -s myserver login -u admin -p $(PASS)
INFO      logging in as admin
Traceback (most recent call last):
File ".../dockpulp/bin/dock-pulp.py", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File ".../dockpulp/bin/dock-pulp.py", line 596, in <module>
main()
File ".../dockpulp/bin/dock-pulp.py", line 47, in main
cmd(opts, args[1:])
File ".../dockpulp/bin/dock-pulp.py", line 361, in do_login
os.makedir(creddir)
AttributeError: 'module' object has no attribute 'makedir'
> Fix mkdir typo in code which created ~/.pulp dir

- setup.py
Example config files are meant to be in package_data, not data_files. Installing to `/etc` means they can't be `pip install`ed in a non-privileged environment such as Travis CI.
See https://github.com/DBuildService/atomic-reactor/issues/209 for the reason behind this change.
> Don't install dockpulp.conf in /etc

- setup.py
The project requires `simplejson`, which may not be installed. Here is one approach for handling that: deal with it in `setup.py`.
The other approach would be to use `json` instead of `simplejson`.
> Add simplejson as a requirement

- bin/dock-pulp-restore.py
- bin/dock-pulp.py
- dockpulp/__init__.py
- dockpulp/imgutils.py
For Python > 2.6, just prefer it.
This is based on https://github.com/release-engineering/dockpulp/pull/12#issuecomment-119216836 "Rats. I have to switch that around."
> Require simplejson on Python 2.6

- dockpulp/__init__.py
The prefix was not passed to createRepo which then created repo `redhat-$repo_prefix-$reponame` instead of `$repo_prefix-$reponame`.
This subsequently caused 404 error in `/pulp/api/v2/repositories/$repo_prefix-$reponame/actions/associate/`.
> Fix push_to_pulp with a repo_prefix

- dockpulp/__init__.py
Using logging.basicConfig adds a handler to the root config, which means it duplicates all messages when dockpulp is imported in atomic reactor and logging is set.
Also, I think this should fix https://github.com/projectatomic/atomic-reactor/issues/271, but I'm not sure and would like to ask you to test that.
> Don't use logging.basicConfig, set handler to the logger instance

- dockpulp/__init__.py
If the repos parameter was a unicode instance it was not being listified.
> Fix listRepos() str-to-list conversion

- dockpulp/__init__.py
The caller doesn't know what the prefix needs to be, so `syncRepo()` should add it if necessary (like `createRepo()` does).
> syncRepo: enforce prefix

- dockpulp/__init__.py
```
$ dock-pulp login -u user -p pswd
Traceback (most recent call last):
File "/usr/bin/dock-pulp", line 723, in <module>
main()
File "/usr/bin/dock-pulp", line 58, in main
cmd(opts, args[1:])
File "/usr/bin/dock-pulp", line 392, in do_login
p = dockpulp.Pulp(env=bopts.server, config_file=bopts.config_file)
File "/usr/lib/python2.7/site-packages/dockpulp/__init__.py", line 157, in __init__
self.load_configuration(config_file)
File "/usr/lib/python2.7/site-packages/dockpulp/__init__.py", line 598, in load_configuration
(sect, env))
NameError: global name 'env' is not defined
```
> don't tback when server is not specified

- dockpulp/__init__.py
```
Traceback (most recent call last):
File "/usr/bin/dock-pulp.py", line 4, in <module>
__import__('pkg_resources').run_script('dockpulp==1.11', 'dock-pulp.py')
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
exec(script_code, namespace, namespace)
File "/usr/lib/python2.7/site-packages/dockpulp-1.11-py2.7.egg/EGG-INFO/scripts/dock-pulp.py", line 678, in <module>
File "/usr/lib/python2.7/site-packages/dockpulp-1.11-py2.7.egg/EGG-INFO/scripts/dock-pulp.py", line 58, in main
File "/usr/lib/python2.7/site-packages/dockpulp-1.11-py2.7.egg/EGG-INFO/scripts/dock-pulp.py", line 343, in do_list
File …
```
> Don't traceback on incomplete distributor config

- dockpulp/__init__.py
This is needed so that 'https://distribution.example.com' doesn't have to be written as 'https://distribution.example.com:443'.
> Don't override the default port for sync

- dockpulp/__init__.py
Previously it failed to list repos:
INFO      getting all repositories...
Traceback (most recent call last):
File "/usr/bin/dock-pulp", line 741, in <module>
main()
File "/usr/bin/dock-pulp", line 58, in main
cmd(opts, args[1:])
File "/usr/bin/dock-pulp", line 406, in do_list
repos = p.listRepos(content=opts.content)
File "/usr/lib/python2.6/site-packages/dockpulp/__init__.py", line 573, in listRepos
r['redirect'] = blob['distributors'][0]['config']['redirect-url']
IndexError: list index out of range
> Continue if there is no distributor for a repo

- bin/dock-pulp.py
- conf/dockpulp.conf
Dock-pulp can now confirm protected repositories, with two caveats.
I had to use subprocess / curl instead of the more preferable python requests because requests does not support encrypted keys. 
Also, the way our entitlements work require the user to be root. What this means for dockpulp is that you'll have to log into the environment as root and run confirm as root for protected repos.
> Dock-Pulp confirm for protected repos

- bin/dock-pulp.py
- dockpulp/__init__.py
Copy can now copy over v2 manifests and blobs. Also removed upstream_name parameter from syncRepos because listRepos() needs to be done regardless.
> Copy supports v2

- bin/dock-pulp.py
- dockpulp/__init__.py
syncRepo now returns a tuple of new images and manifests instead of old repo information.
> Updated sync to always copy new images and manifests to HIDDEN repo

- bin/dock-pulp-recreate-hidden.py
- dockpulp/__init__.py
This vastly improves the speed of recreating the hidden repository.
> copy_filters: new method, used by recreate-hidden script

- dockpulp/__init__.py
The configuration option name is enable_v1 not enabled_v1:
https://github.com/pulp/pulp_docker/blob/master/docs/tech-reference/importer.rst
Reorganised code to avoid repetition.
> sync: fix enable_v1 setting

- bin/dock-pulp.py
I had the situation last week where I asked dock-pulp to remove a single layer from the hidden repository, and afterwards it decided to delete hundreds more layers.
> CLI: 'remove' should not calculate unneeded layers for hidden repo

- bin/dock-pulp.py
The check that the manifest's 'name' field matches the docker-id should only occur if the manifest actually exists.
> confirm: avoid traceback for unpublished v2 content

- dockpulp/imgutils.py
Recent docker versions seem to strip docker_version from all layers
except the last one during v1-to-v2 migration. We should ignore layers
that don't have docker_version key
> get_versions: skip layers if they don't have docker_version set

- bin/dock-pulp.py
- dockpulp/__init__.py
Instead of changing the tags that listRepos() reports, add a new 'tags' dict which maps tag names onto manifest digests.
In the CLI, use this new dict to decide which manifests have tags that are active.
> Fix confirm errors caused by '(active)' changes

- bin/dock-pulp.py
Can be overridden with 'dock-pulp update' if needed.
> content-url is now enforced to end with '/docker-id'

- setup.py
Move version in VERSION file, and use version specified here
in spec file and setup.py.
This fixes pulling in run-time dependencies during setup in
setup.py.
> Remove import of version from setup.py

- dockpulp/__init__.py
- tests/test_pulp_instance.py
This change is to resolve issue 2661.
Pulp fails silently on redirect-url updates if it does not fit a specific format, so dockpulp now front-ends that check for a better user experience.
> Dockpulp checks update redirect-url to fit pulp standards

- bin/dock-pulp.py
- dockpulp/__init__.py
- tests/test_pulp_instance.py
dockpulp list now displays label information for V2.
As far as I can tell, there is no way to obtain label information from Pulp for V1 images.
> Added listing label support for v2 manifests

- bin/dock-pulp-bootstrap
- dockpulp/__init__.py
- dockpulp/cli.py
- tests/test_pulp_instance.py
Replaced all instances of HIDDEN repo dependence with origin repos based on each existing repo.
If the origin repo does not exist it will be automatically created during those operations.
> Deprecating HIDDEN repo and replacing with 'origin' repos

- dockpulp/__init__.py
- tests/test_pulp_instance.py
syncRepo: copy new files with an explicit filter
apparently pulp does not do a good job of filtering out old files
when copying them to a new repo. In syncRepo, add a filter containing
the new images, new manifests, and new manifest lists.
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>
> syncRepo: copy new files with an explicit filter

- dockpulp/__init__.py
- tests/test_pulp_instance.py
Instead of fetching the entire repository before and after the sync and comparing them, find new units by fetching the repository content after the sync, limiting the search to those units updated since the start of the sync task.
To help with this, add a new 'since' parameter to listRepos(), and make watch() return the task report.
> Improve sync efficiency

- dockpulp/__init__.py
If a repository contains images which are not necessarily strictly
complete in their ancestry, avoid a traceback when computing image
ancestry.
This can be the case for repositories which only hold copies of units
and are never intended to be published.
> Avoid traceback when computing ancestry

- dockpulp/__init__.py
The previous approach of using '$and' causes Pulp to reply with 500
error indicating $and is an "unknown operator". The fix is to use the
existing filter object for _last_updated field.
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Fix content list pagination with since filter

- dockpulp/__init__.py
- dockpulp/cli.py
- tests/test_cli.py
It's extremely annoying to have to log in each time I switch servers.
Reconciling problems efficiently between environments (especially prod
and stage) results in sensitive passwords being stored in plaintext in
scripts and aliases. This simple patch uses the environment name to
distinguish between credential storage files.
> Separate credentials by server

- dockpulp/cli.py
Pulp is now providing a dictionary including arch information instead of a simple string digest, dock-pulp needs to accommodate this.
> Quick fix for Pulp manifest list change

- .travis.yml
- dockpulp/__init__.py
To avoid mongo limitation which results in error: BSON document too large
we need to limit number of image signatures removed in one request from
a repository
> Remove image signatures in batches

- dockpulp/__init__.py
- tests/test_pulp_instance.py
Task watch function returns immediately when task is in state
skipped or canceled.
> Not wait for tasks in terminal states

- dockpulp/cli.py
- tests/test_cli.py
'qa' was the default value of server. It could be confusing if it's not noticed. E.g. a user may login to the default environment without specifying --server, but not aware it's 'qa', then get error of 'need to log in' when doing other operations with a --server other than 'qa'. Make --server required to avoid the confusion.
> Report error when --server isn't specified

- dockpulp/cli.py
- tests/test_cli.py
Pulp is no longer the source of truth for repo metadata, so updating
the metadata through dockpulp should no longer be supported
Refers to CLOUDDST-1155
> Remove update repo metadata functionality

- dockpulp.spec
- setup.py
This also simplifies how the python package is built and how the files are collected in order to create the RPM package. On RHEL-6 and RHEL-7, the RPMs will end up looking mostly the same (they will include additional egg-info files). On RHEL-8 as well as modern Fedoras the package will become buildable and will work with python 3.
> Update RPM spec file to work with RHEL-8 / python 3 builds

- dockpulp.spec
- rel-eng/releasers.conf
It it turns out that the usual installation method  `setup.py install --record=INSTALLED_FILES` records just the files, but not the directories which contain those files. This results in empty egg-info directories left in /usr/lib/python3.6/site-packages after an RPM with python module is updated to a newer version.
This change ensures egg-info directories are included and also removes the RHEL6 package target as we are moving away from it.
> Update spec file and remove RHEL6
