bin/dock-pulp.py, dockpulp/__init__.py
Allows test CLI without having config file in the system path.
=> Configurable path to config file

dockpulp/imgutils.py
Sorry! Missed this in testing.
=> Import sys before checking sys.version_info

dockpulp/__init__.py
Needed in order to move push_tar_to_pulp out of dockpulp.
=> Factor out repo search into getRepos

bin/dock-pulp.py, dockpulp/__init__.py
@midnightercz, are you OK with bringing this into master?
=> Port certificate-based auth from Jindra's fork

dockpulp/__init__.py
I've added a commit that fixes some incorrect information in comments and removes the old function.
@midnightercz, OK to port this to master?
=> watch_tasks implementation that returns when any task fails

dockpulp/__init__.py
=> Fix initialization of syncenv instance variable

dockpulp/__init__.py
=> syncRepo: don't change the sync environment (#47)

bin/dock-pulp.py, dockpulp/__init__.py
This would help atomic-reactor upload less layers
=> Check if layers already exists on the server

bin/dock-pulp.py
Removed need for curl in confirm function, now accepts cert and key and uses python requests. Added in machine readable output for confirm as a --silent option.
=> Updated confirm to use requests and silent option

bin/dock-pulp.py
There was some confusion about glob vs regex, made help text more accurate.
=> Fixed some typos regarding regex/glob

bin/dock-pulp.py, dockpulp/__init__.py
List will show digests, tag for each digest, and layers attributed to each digest. (Uses manifests).
=> Added v2 support for dockpulp list

dockpulp/__init__.py
This is to fulfill atomic reactor requirements.
=> Updated sync to allow auth

bin/dock-pulp.py
New option to specifically test v1 or v2 content.
=> Updated confirm for v2 manifests and blobs

dockpulp/__init__.py, setup.py
See https://www.python.org/dev/peps/pep-0396/
=> Set __version__ attribute in dockpulp module

bin/dock-pulp-recreate-hidden.py, dockpulp/__init__.py
Fixed issue on systems with python 2.6 or lower.
=> Fixed logging for python <2.7

bin/dock-pulp.py
Fixed issue with silent output not reporting v1 error if v2 content is fine as well.
=> Confirm does not test if there is no v1 or v2 content.

bin/dock-pulp.py, dockpulp/__init__.py
Previously listRepos() did not ask Pulp which blobs were present in the repository at all, and just assumed that any blobs referenced from the manifests were present.
This change alters that so that only the blobs which are actually present in Pulp are listed.
Blobs that are not present, but are referenced by a manifest, cause a warning to be emitted.
As part of refactoring this, I also combined the three separate Pulp API requests into a single request for speed/efficiency.
=> Report missing v2 blobs

bin/dock-pulp-bootstrap.py, bin/dock-pulp-recreate-hidden.py, bin/dock-pulp-restore.py, bin/dock-pulp.py, dockpulp/__init__.py, dockpulp/errors.py, dockpulp/imgutils.py, setup.py
=> whitespace changes only

dockpulp/__init__.py
=> Added configurable retries to make requests more resilient

bin/dock-pulp.py
Misunderstood initial requirement.
=> Fixed createrepo enforcement

dockpulp/__init__.py, dockpulp/cli.py
PTAL @breillyr @lcarva @rcerven
=> New pulp (2.13) doesn't store tags along with manifest, so it should be looked up additionally

dockpulp/__init__.py, tests/test_pulp_instance.py
I'm not sure how to mimic connection failures with flexmock in such a way for the adapter to handle them so I've commented out the relevant unit tests for now.
=> Changed request retry implementation

dockpulp.spec, dockpulp/__init__.py, tests/test_pulp_instance.py
Just an initial patchset - I will be updating the PR with unit tests.
=> Improved sigstore repo checking

dockpulp/__init__.py
Example of configuration in dockpulp.conf:
```
[dist_switchover]                                                                                       
2.14 = foo_distributor,bar_distributor
```
=> Added optional config for pulp distributor switchovers

dockpulp/__init__.py
=> Log the actual status code when >= 500

dockpulp/__init__.py, dockpulp/cli.py, tests/test_cli.py, tests/test_pulp_instance.py
Added ability to set and list new reponotes value "include_in_download_service"
=> Dlservice5041

dockpulp/cli.py, tests/test_cli.py
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
=> Output tasks json in silent mode

dockpulp/cli.py
=> Include additional unit types for orphan management

dockpulp/__init__.py, tests/test_pulp_instance.py
=> syncRepo: make a list of keys before sorting

dockpulp/cli.py
Before:
None
After:
10.6.0-3
(for example)
=> Better output when listing orphan docker tags

dockpulp/__init__.py, dockpulp/cli.py, tests/test_cli.py, tests/test_pulp_instance.py
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
=> Paginate repo contents to avoid pulp memory issues

.travis.yml, bin/dock-pulp-recreate-hidden, bin/dock-pulp-restore, dockpulp/__init__.py, dockpulp/cli.py, dockpulp/imgutils.py, tests/test_cli.py, tests/test_imgutils.py, tests/test_pulp_instance.py, tox.ini
Done using the [2to3 script](https://docs.python.org/2/library/2to3.html)
=> Made dockpulp python 3 compatible [WIP]

dockpulp/cli.py
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
=> Fix arg parsing for --no-paginate

dockpulp/__init__.py, tox.ini
=> Flake8 pass

dockpulp/__init__.py
=> Make sure not to issue a remove request for zero signatures

dockpulp/__init__.py
Accidentally removed when merging.
=> Restore commit 1316cf

dockpulp/__init__.py, tests/test_pulp_instance.py
We want to skip malformed repos with warning to support automated registry testing
=>  list skips repos without repo type

conf/dockpulp.conf, dockpulp/__init__.py, tests/test_pulp_instance.py
The validation is essential to create secure SSL/TLS sessions.
=> Enable SSL certificate validation

bin/dock-pulp-bootstrap, conf/dockpulp.conf, dockpulp/__init__.py, dockpulp/cli.py, tests/test_cli.py, tests/test_pulp_instance.py
The legacy sigstore (a special Pulp repo) is not in use anymore.
=> Remove references to legacy sigstore [CLOUDDST-7416]

tests/test_pulp_instance.py
Mocking a tar file was broken for test_checkLayers(). Let's now use temporary files to create a real tar file which is used in the test.
=> Fix file mocking in test
